###
POST http://localhost:5001/futurama-chatbot/us-central1/dialogflowFirebaseFulfillment
Content-Type: application/json

{
  "queryResult": {
    "parameters": {
      "character": "bender",
      // quote: 'At last, war has made me into a man. Weeeeee!',
    },
  },
}

###
GET futuramaapi.herokuapp.com/api/characters/bender/1
Content-Type: application/json
